// generated by ti18n 🎯

// this is an extension locale and therefore gets its type from the default locale ("./de-de")
import type { Translations } from "./de-de";

export const translations : Translations = {
	staticStrings: `Translations for "de-at"`,
	functions: (hello: string, world: string) => `Say ${hello} to ${world}`,
	nest: {
		keys: {
			as: {
				deep: {
					as: {
						you: {
							like: `No magic, just your structure`
						},
					},
				},
			},
		},
	},
}
