// generated by ti18n 🎯

export type Locale = `de-de` | `de-at` | `de-ch`

function importTranslations (locale: Locale) {
	switch (locale) {
		case `de-de`: return import(`./de-de`)
		case `de-at`: return import(`./de-at`)
		case `de-ch`: return import(`./de-ch`)
	}
}

export function translations (locale: Locale) {
	return importTranslations(locale).then(({ translations }) => translations)
}
