// generated by ti18n 🎯

// this is the default locale, its data type will be expected on the extension locales

const i18n = {
	staticStrings: `Translations for "en, US"`,
	functions: (hello: string, world: string) => `Say ${hello} to ${world}`,
	nest: {
		keys: {
			as: {
				deep: {
					as: {
						you: {
							like: `No magic, just your structure`
						},
					},
				},
			},
		},
	},
	jsx: () => <div>Components are cool, too</div>
}

//

// look but don't touch. the following makes the i18n objects readonly
const _i18n : I18n = i18n
export { _i18n as i18n }

export type I18n = DeepReadonly<typeof i18n>

// there are more sophisticated versions, but this is good enough
type DeepReadonly<T> = (
	T extends (...args: infer A) => infer R
	? (...args: A) => DeepReadonly<R>
	: { readonly [K in keyof T]: DeepReadonly<T[K]> }
)
