// generated by sammich 🎯

// this is an extension locale and therefore gets its type from the default locale ("./en, US")
import type { I18n } from "./en, US.jsx";

export const i18n : I18n = {
	staticStrings: `Translations for "en, UK"`,
	functions: (hello: string, world: string) => `Say ${hello} to ${world}`,
	nest: {
		keys: {
			as: {
				deep: {
					as: {
						you: {
							like: `No magic, just your structure`
						},
					},
				},
			},
		},
	},
	jsx: () => <div>Components are cool, too</div>
}
