// generated by ti18n 🎯

// this is an extension locale and therefore gets its type from the default locale ("./en")
import type { I18n } from "./en.js";

export const i18n : I18n = {
	staticStrings: `Translations for "de"`,
	functions: (hello: string, world: string) => `Say ${hello} to ${world}`,
	nest: {
		keys: {
			as: {
				deep: {
					as: {
						you: {
							like: `No magic, just your structure`
						},
					},
				},
			},
		},
	},
}
