import fsExtra, { ensureDir } from "fs-extra"
import { SammichConfigInternal } from "./buildConfig.js";

export type FileObject = {
	readonly name: string
	readonly path: string
	readonly content: string
}

const { writeFile } = fsExtra

const watermark = `// generated by sammich 🎯`

export function writeFiles ({ path }: SammichConfigInternal, files: ReadonlyArray<FileObject>) {
	return Promise.all(
		files
		.map(async file => {
			await ensureDir(path(file.path))

			return writeFile(
				path(
					file.path,
					file.name
				),
				`${watermark}\n\n${file.content}`
			)
		})
	);
}
